### ISSUE TITLE
Vanilla versions?

### ISSUE THREAD

**Issue by danigosa** [JayH5/docker-alpine-pypy#16]
Just a suggestion, i.e. in our organizations _we do not like buildpacks_ for any Os for production images, therefore we do not like images from the Hub based on buildpacks. In your case it would not painful to include a vanilla version directly from alpine hub registry, this way we can (and I suspect others) use your hub images instead of having to just look at your samples and make the evolutions by hand. **Good job by the way** 👍

**Comment by JayH5** [comment]
Hey 👋, if I understand you right, what you're looking for is the `slim` variants:
```
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
jamiehewland/alpine-pypy   2-5.9.0             157cc280cf02        43 hours ago        791MB
jamiehewland/alpine-pypy   2-5.9.0-slim        7d907f6e2f3c        43 hours ago        132MB
```

The image tags here work like the ones for the official `python` or `pypy` images: the default one has buildpack things, the slim one does not.

**Comment by danigosa** [comment]
True! I did not see this, so now I'm expecting then the pypy3-slim with pypy 5.9 based on alpine3.6, may you can add a line in the README for the 2 types of images you provide, thx!

**Comment by JayH5** [comment]
@danigosa yeah I'll add a note in the README sometime soon (pull requests also welcome).

I haven't managed to compile PyPy3 5.9.0 on Alpine Linux yet...there are some new things that need patching, unfortunately, so `jamiehewland/alpine-pypy:3-5.8.0-slim` based on Alpine 3.4 is the best I have right now 😕

**Comment by danigosa** [comment]
@JayH5 well I can say that your pypy3 5.8.0 compilation **do work on alpine3.6**, we are keeping on it (pypy58 & alpine36) for now
